version: '3'
services:
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:3000:3000'
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  flyway:
    build:
      context: ./db
      dockerfile: Dockerfile
    depends_on:
      - db

volumes:
  postgres_data:
